name: 🐛 Отчет об ошибке (Bug Report)
description: Сообщить об ошибке или сбое в работе CapyLib
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Спасибо за сообщение об ошибке! Заполните поля ниже как можно подробнее.
  - type: textarea
    id: description
    attributes:
      label: Описание проблемы
      description: Что именно пошло не так?
      placeholder: Подробное описание бага...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Шаги для воспроизведения
      description: Как воспроизвести данную ошибку?
      placeholder: |
        1. Зайти на сервер...
        2. Использовать предмет...
        3. Ошибка в логах...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Логи сервера (EXILED)
      description: Прикрепите фрагмент лога с ошибкой
      render: text
