name: 💡 Предложение новой функции (Feature Request)
description: Предложить новую идею или улучшение для CapyLib
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature
    attributes:
      label: Описание идеи
      description: Какую механику или улучшение вы предлагаете добавить?
      placeholder: Подробное описание новой функции...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Желаемый результат
      description: Как именно эта функция должна работать на сервере?
